# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Manic Ravings
tagline:          I am nothing and should be everything
description:      Anything
url:              http://manics.github.io

author:
  name:           Simon Li
  url:            https://twitter.com/crucifixkiss

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/manics/manics.github.io
